docs(xstate-test): add note about nested states
davidkpiano/xstate pull request #1535
Opened 2020-10-07 23:20 UTC by UberMouse

This tripped me up before and caused me to spend a few hours debugging @xstate/test and my tests to determine why it seemed like tests were being run for the wrong state.

Turns out that @xstate/test executes not just the `meta.test` for the current state, but also all the parent states of the current state. Seems like a good thing to note in the docs as it's not immediately obvious (but makes sense now in retrospect).

2020-10-08 01:01 UTC, davidkpiano commented
Thanks! Can you do this in `packages/xstate-test/README.md` instead?

2020-10-08 01:07 UTC, UberMouse commented
Have changed the README instead of the docs page now.

2020-10-09 12:28 UTC, davidkpiano requested changes
One quick change, and then it should be good to go!

2020-10-09 12:28 UTC, davidkpiano commented on packages/xstate-test/README.md
> +NOTE: If your model has nested states, the `meta.test` method for each parent state is also executed when veryifing the SUT is in the target `testPath.state`
```suggestion
NOTE: If your model has nested states, the `meta.test` method for each parent state of that nested state is also executed when verifying that the SUT is in that nested state.
```

2020-10-21 00:20 UTC, UberMouse commented
Sorry @davidkpiano, missed the notification. I've just accepted your change.

2020-10-21 01:18 UTC, merged