Updates Docs about Svelte Setup & Template
davidkpiano/xstate pull request #3930
Opened 2023-03-28 22:08 UTC by TobiObeck

This PR fixes documentation issues regarding Svelte project setup and templates that I recently chatted about with David in a [Discord Thread](https://discord.com/channels/795785288994652170/1087844443933118596/1087882795365441567).

This PR should be considered in conjunction with a PR ("Updates Svelte Template link") in the new docs repo (linking to the template introduced in this PR).
https://github.com/statelyai/docs/pull/74

2023-03-28 23:28 UTC, davidkpiano commented on docs/recipes/svelte.md
> +In this section you find information for setting up XState in a Svelte project. Nowadays the Svelte docs recommend the usage of Vite for new Svelte or SvelteKit projects. The section directly below i
```suggestion
In this section, we provide guidance on setting up XState in a Svelte project. For new Svelte or SvelteKit projects, we recommend using [Vite](https://vitejs.dev/guide/) as your build tool. This documentation is tailored to such projects. If you're working on an older project that relies on Rollup, please refer to the section further below.
```

2023-03-31 15:36 UTC, davidkpiano approved these changes

2023-03-31 15:38 UTC, laurakalbag requested changes
@TobiObeck thank you so much for this! We really appreciate it. I’ve made a few suggested changes just for the text because I’m an annoying nerd.

2023-03-31 15:38 UTC, laurakalbag commented on docs/recipes/svelte.md
> +In this section, we provide guidance on setting up XState in a Svelte project. For new Svelte or SvelteKit projects, we recommend using [Vite](https://vitejs.dev/guide/) as your build tool. This docu
```suggestion
This guides you through setting up XState in a Svelte project. For new Svelte or SvelteKit projects, we recommend using [Vite](https://vitejs.dev/guide/) as your build tool, and we’ve tailored this documentation to such projects. If you're working on an older project that relies on Rollup, please refer to the [Legacy Svelte projects based on Rollup section](#legacy-svelte-projects-based-on-rollup) below.
```

2023-03-31 15:38 UTC, laurakalbag commented on docs/recipes/svelte.md
> +XState integrates great with Svelte & SvelteKit, and especially [Svelte stores!](https://svelte.dev/docs#svelte_store). The official `@xstate/svelte` package is recommended to get the most out of XSt
```suggestion
XState integrates great with Svelte & SvelteKit, and especially [Svelte stores](https://svelte.dev/docs#svelte_store). We recommend the official `@xstate/svelte` package to get the most out of XState and Svelte.
```

2023-03-31 15:38 UTC, laurakalbag commented on docs/recipes/svelte.md
> +- Details about the installation and usage example can be found in the new docs on the page about the [xstate svelte package](https://stately.ai/docs/xstate/packages/xstate-svelte).
```suggestion
- Find installation details and example usage in the new docs on the [xstate svelte package](https://stately.ai/docs/xstate/packages/xstate-svelte).
```

2023-03-31 15:38 UTC, laurakalbag commented on docs/recipes/svelte.md
> +- You can also check out a [template](https://stately.ai/docs/xstate/templates) for quickly gettings started with a minimal project.
```suggestion
- Check out a [template](https://stately.ai/docs/xstate/templates) to get started quickly with a minimal project.
```

2023-03-31 15:38 UTC, laurakalbag commented on docs/recipes/svelte.md
> +## Legacy: Svelte projects based on Rollup
```suggestion
## Legacy Svelte projects based on Rollup
```

2023-04-03 12:37 UTC, TobiObeck commented
Hey @laurakalbag , thanks for your suggestions. I like your briefer formulations and committed them all. There are only two sections where I think a bit longer version sounds more natural to me or maybe flows a bit better. But I don't have a strong opinion on it. So, leaving everything the way it is, would also be fine.

```
- This guides you through
+ This section guides you through
```

```
- Find installation details...
+ You can find installation details
```

2023-04-03 12:56 UTC, laurakalbag approved these changes
Thank you so much, @TobiObeck!

2023-04-03 12:56 UTC, merged